# Generated by Django 2.2.1 on 2019-05-23 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_artical_banner_category_link_recom_tag'),
    ]

    operations = [
    ]
