# Generated by Django 2.2.1 on 2019-05-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20190523_2329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '轮播图表', 'verbose_name_plural': '轮播图表'},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': '友情链接表', 'verbose_name_plural': '友情链接表'},
        ),
        migrations.AlterField(
            model_name='artical',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='artical-img/%Y-%m', verbose_name='文章图片'),
        ),
    ]
