# Generated by Django 2.2.1 on 2019-05-24 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_auto_20190524_1133'),
    ]

    operations = [
    ]
