# Generated by Django 2.2.1 on 2019-05-24 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_auto_20190524_1150'),
    ]

    operations = [
    ]
