# Generated by Django 2.2.1 on 2019-05-24 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_auto_20190524_2118'),
    ]

    operations = [
    ]
