# Generated by Django 2.2.1 on 2019-05-24 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_auto_20190524_2149'),
    ]

    operations = [
    ]
